### PR TITLE
[Bug fix] Fixes bug with cert directory

### PR DESCRIPTION
**Pull request by gruyaume**
# Description

Fixes bug with cert directory. The current cert directory assumed the path of the binary from before we were using the ROCK.

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [ ] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have bumped the version of the library

### CODE REVIEW

**Comment by saltiyazan** [comment]
Are you sure this is needed? the integration tests seem to pass with `/free5gc/support`. or would the tests pass if the service didn't start? 
Is the path hardcoded also using a path relative to the location of the binary as in `nrf`?

**Comment by gruyaume** [comment]
> Are you sure this is needed? the integration tests seem to pass with `/free5gc/support`. or would the tests pass if the service didn't start? Is the path hardcoded also using a path relative to the location of the binary as in `nrf`?

Yes the service technically starts but there are error messages in the logs. Ultimately you couldn't run a simulation with the service as it was.

**Comment by saltiyazan** [comment]
> Are you sure this is needed? the integration tests seem to pass with `/free5gc/support`. or would the tests pass if the service didn't start? Is the path hardcoded also using a path relative to the location of the binary as in `nrf`?

I see integration passing now as well, that's interesting :) Then maybe they are not catching such a case.

**Review by saltiyazan — APPROVED** [review]

**Comment by gruyaume** [comment]
> > Are you sure this is needed? the integration tests seem to pass with `/free5gc/support`. or would the tests pass if the service didn't start? Is the path hardcoded also using a path relative to the location of the binary as in `nrf`?
> 
> I see integration passing now as well, that's interesting :) Then maybe they are not catching such a case.

Correct they are not catching this mistake because the pebble service starts properly.

**Pull request merged**
